services:
  # Application Dockerfile is in same folder which is .
  app:
    build: .
    depends_on:
      - db

  # db is is db folder
  db:
    build: ./db
    restart: always
    ports:
      - "33060:3306"